#!/usr/bin/env python3
import argparse
import re
import shutil
import subprocess
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
A_BASE = 100


def read_array_size():
    definitions = (REPO_ROOT / "verilog" / "sys_defs.svh").read_text(encoding="utf-8")
    match = re.search(r"^\s*`define\s+ARRAY_SIZE\s+(\d+)\s*$", definitions, re.MULTILINE)
    if not match:
        raise RuntimeError("could not read ARRAY_SIZE from verilog/sys_defs.svh")
    size = int(match.group(1))
    if size <= 0:
        raise RuntimeError("ARRAY_SIZE must be a positive integer")
    return size


T = read_array_size()


SOURCES = [
    "verilog/mac.sv",
    "verilog/activation_buffer.sv",
    "verilog/weight_buffer.sv",
    "verilog/input_skew_buffer.sv",
    "verilog/bias_add.sv",
    "verilog/activation.sv",
    "verilog/scratchpad.sv",
    "verilog/tpu_command_queue.sv",
    "verilog/array_scheduler.sv",
    "verilog/tpu_controller.sv",
    "verilog/systolic_array.sv",
    "verilog/tpu.sv",
    "verilog/tpu_system.sv",
    "test/matrix_multiply_test.sv",
]


def parse_matrix(text, name):
    rows = [row.strip() for row in text.strip().split(";") if row.strip()]
    if not rows:
        raise ValueError(f"{name} must contain at least one row")

    matrix = []
    column_count = None
    for idx, row in enumerate(rows):
        values = [v for v in re.split(r"[\s,]+", row) if v]
        if column_count is None:
            column_count = len(values)
        if not values or len(values) != column_count:
            raise ValueError(
                f"{name} row {idx + 1} must have {column_count} values; "
                f"got {len(values)}"
            )
        matrix.append([int(v, 0) for v in values])
    return matrix


def prompt_positive_int(prompt):
    while True:
        try:
            value = int(input(prompt).strip())
            if value > 0:
                return value
        except ValueError:
            pass
        print("Please enter a positive integer.")


def prompt_dimensions():
    print("Enter dimensions for A[M x K] multiplied by B[K x N].")
    m = prompt_positive_int("Rows in A (M): ")
    k = prompt_positive_int("Columns in A / rows in B (K): ")
    n = prompt_positive_int("Columns in B (N): ")
    return m, k, n


def prompt_matrix(name, rows, columns):
    print(f"\nEnter matrix {name} ({rows}x{columns}), one row at a time.")
    matrix = []
    for row_index in range(rows):
        while True:
            row = input(f"{name} row {row_index + 1}: ").strip()
            values = [value for value in re.split(r"[\s,]+", row) if value]
            if len(values) != columns:
                print(f"Please enter exactly {columns} integers; you entered {len(values)}.")
                continue
            try:
                matrix.append([int(value, 0) for value in values])
                break
            except ValueError:
                print("Please use integers only (for example: 1 2 3 4).")
    return matrix


def matrix_shape(matrix):
    return len(matrix), len(matrix[0])


def matmul(a, b):
    a_rows, inner = matrix_shape(a)
    b_rows, b_columns = matrix_shape(b)
    if inner != b_rows:
        raise ValueError(
            f"incompatible dimensions: A is {a_rows}x{inner}, but B is "
            f"{b_rows}x{b_columns} (A columns must equal B rows)"
        )
    return [
        [sum(a[r][k] * b[k][c] for k in range(inner)) for c in range(b_columns)]
        for r in range(a_rows)
    ]


def print_matrix(label, matrix):
    print(f"{label}:")
    for row in matrix:
        print("  [ " + " ".join(f"{value:>6}" for value in row) + " ]")


def sv_u32(value):
    return value & 0xFFFFFFFF


def round_up(value, multiple):
    return ((value + multiple - 1) // multiple) * multiple


def write_matrix_config(path, m, k, n, padded_m, padded_n):
    a_words = padded_m * k
    b_words = k * padded_n
    c_words = padded_m * padded_n
    if k > 255 or padded_m // T > 255 or padded_n // T > 255:
        raise ValueError("matrix dimensions exceed the TPU command field limits")
    if A_BASE + a_words + b_words + c_words + 16 > (1 << 16):
        raise ValueError("matrices are too large for the TPU's 16-bit scratchpad addresses")

    path.write_text(
        "// Generated by scripts/run_matrix_multiply.py\n"
        f"`define MATRIX_M {m}\n"
        f"`define MATRIX_K {k}\n"
        f"`define MATRIX_N {n}\n"
        f"`define PADDED_M {padded_m}\n"
        f"`define PADDED_N {padded_n}\n",
        encoding="utf-8",
    )


def write_matrix_include(path, a, b, c, padded_m, padded_n):
    m, k_size = matrix_shape(a)
    _, n = matrix_shape(b)
    b_base = A_BASE + (padded_m * k_size)
    with path.open("w", encoding="utf-8") as f:
        f.write("// Generated by scripts/run_matrix_multiply.py\n")
        f.write("// A is stored as T-row column vectors, with zero-padded edge lanes.\n")
        for mt in range(padded_m // T):
            for k in range(k_size):
                for lane in range(T):
                    row = mt * T + lane
                    value = a[row][k] if row < m else 0
                    address = A_BASE + ((mt * k_size + k) * T) + lane
                    f.write(f"        host_write(16'd{address}, 32'd{sv_u32(value)});\n")

        f.write("// B is stored as T-column row vectors, with zero-padded edge lanes.\n")
        for k in range(k_size):
            for nt in range(padded_n // T):
                for lane in range(T):
                    col = nt * T + lane
                    value = b[k][col] if col < n else 0
                    address = b_base + ((k * (padded_n // T) + nt) * T) + lane
                    f.write(f"        host_write(16'd{address}, 32'd{sv_u32(value)});\n")

        f.write("// Expected unpadded C = A * B, row-major.\n")
        for r in range(m):
            for col in range(n):
                f.write(f"        expected[{r*n + col}] = 32'd{sv_u32(c[r][col])};\n")


def extract_result(output):
    rows = []
    in_block = False
    for line in output.splitlines():
        stripped = line.strip()
        if stripped == "MATRIX_RESULT_BEGIN":
            in_block = True
            continue
        if stripped == "MATRIX_RESULT_END":
            break
        if in_block:
            rows.append(stripped)
    return rows


def select_simulator(requested):
    if requested != "auto":
        if shutil.which(requested):
            return requested
        raise RuntimeError(f"{requested} is not installed or is not on PATH")

    for simulator in ("verilator", "vcs"):
        if shutil.which(simulator):
            return simulator

    raise RuntimeError(
        "neither Verilator nor VCS is on PATH. Install Verilator for free, or "
        "load VCS on a machine with a Synopsys license"
    )


def run_vcs(repo_root):
    simv = repo_root / "build" / "matrix_multiply.simv"
    out_file = repo_root / "build" / "matrix_multiply.out"

    compile_cmd = [
        "vcs",
        "-sverilog",
        "-full64",
        "-kdb",
        "-lca",
        "-nc",
        "-debug_access+all",
        "+incdir+verilog/includes",
        "+incdir+verilog",
        *SOURCES,
        "-o",
        str(simv),
    ]
    subprocess.run(compile_cmd, cwd=repo_root, check=True)

    run_cmd = [str(simv), "+vcs+vcd", "+dumpfile=vcd/matrix_multiply.vcd"]
    result = subprocess.run(
        run_cmd,
        cwd=repo_root,
        check=True,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
    )
    out_file.write_text(result.stdout, encoding="utf-8")
    print(result.stdout, end="")
    return result.stdout


def run_verilator(repo_root, verbose=False):
    build_dir = repo_root / "build" / "verilator_matrix_multiply"
    simv = build_dir / "matrix_multiply.simv"
    out_file = repo_root / "build" / "matrix_multiply.out"
    compile_log = repo_root / "build" / "verilator_compile.out"

    compile_cmd = [
        "verilator",
        "--binary",
        "--timing",
        "--trace-vcd",
        "-Wno-fatal",
        "--top-module",
        "matrix_multiply_test",
        "--Mdir",
        str(build_dir),
        "-o",
        simv.name,
        "-I.",
        "-Iverilog",
        *SOURCES,
    ]
    compile_result = subprocess.run(
        compile_cmd,
        cwd=repo_root,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
    )
    compile_log.write_text(compile_result.stdout, encoding="utf-8")
    if verbose or compile_result.returncode != 0:
        print(compile_result.stdout, end="", file=sys.stderr)
    elif compile_result.stdout.strip():
        print(f"Verilator compile details: {compile_log}")
    if compile_result.returncode != 0:
        raise subprocess.CalledProcessError(
            compile_result.returncode,
            compile_cmd,
            output=compile_result.stdout,
        )

    run_cmd = [str(simv), "+dumpfile=vcd/matrix_multiply.vcd"]
    result = subprocess.run(
        run_cmd,
        cwd=repo_root,
        check=True,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
    )
    out_file.write_text(result.stdout, encoding="utf-8")
    print(result.stdout, end="")
    return result.stdout


def main():
    parser = argparse.ArgumentParser(description="Multiply two integer matrices.")
    parser.add_argument("a", nargs="?", help="Matrix A rows separated by semicolons.")
    parser.add_argument("b", nargs="?", help="Matrix B rows separated by semicolons.")
    parser.add_argument(
        "--software-only",
        action="store_true",
        help="Deprecated alias for the default Python calculation mode.",
    )
    parser.add_argument(
        "--rtl",
        action="store_true",
        help="Also compile and verify the result using the TPU RTL.",
    )
    parser.add_argument(
        "--sim",
        choices=("auto", "verilator", "vcs"),
        default="auto",
        help="RTL simulator to use (default: auto, preferring Verilator).",
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Show simulator compilation output instead of only saving it to a log.",
    )
    args = parser.parse_args()

    try:
        if args.a is None and args.b is None:
            m, k, n = prompt_dimensions()
            a = prompt_matrix("A", m, k)
            b = prompt_matrix("B", k, n)
        elif args.a is not None and args.b is not None:
            a = parse_matrix(args.a, "A")
            b = parse_matrix(args.b, "B")
        else:
            raise ValueError("provide both matrix A and matrix B, or omit both for interactive mode")

        c = matmul(a, b)
    except ValueError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    a_rows, a_columns = matrix_shape(a)
    _, b_columns = matrix_shape(b)
    padded_m = round_up(a_rows, T)
    padded_n = round_up(b_columns, T)

    repo_root = REPO_ROOT

    print_matrix("Matrix A", a)
    print_matrix("Matrix B", b)
    print("\nEXPECTED RESULT:")
    print_matrix("C = A x B", c)

    if not args.rtl:
        print("\nCalculated with Python.")
        print("Use --rtl to also verify this result on the TPU RTL.")
        return 0

    (repo_root / "build").mkdir(exist_ok=True)
    (repo_root / "vcd").mkdir(exist_ok=True)
    try:
        write_matrix_config(
            repo_root / "build" / "matrix_config.svh",
            a_rows, a_columns, b_columns, padded_m, padded_n,
        )
        write_matrix_include(
            repo_root / "build" / "matrix_input.svh", a, b, c, padded_m, padded_n,
        )
    except ValueError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    print(
        f"TPU array size: {T}x{T}\n"
        f"RTL tiling: {a_rows}x{a_columns} * {a_columns}x{b_columns} "
        f"uses a {padded_m}x{b_columns} A edge layout and "
        f"{a_columns}x{padded_n} B edge layout"
    )

    try:
        simulator = select_simulator(args.sim)
        print(f"RTL simulator: {simulator}")
        if simulator == "verilator":
            output = run_verilator(repo_root, verbose=args.verbose)
        else:
            output = run_vcs(repo_root)
    except (RuntimeError, subprocess.CalledProcessError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        print(
            "hint: the matrix result above is still available, but RTL verification "
            "requires Verilator or a working VCS installation/license.",
            file=sys.stderr,
        )
        return 127 if isinstance(exc, RuntimeError) else exc.returncode

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
