#!/usr/bin/env python3
import argparse
import re
import shutil
import subprocess
import sys
from pathlib import Path


T = 4
A_BASE = 100
B_BASE = 200


SOURCES = [
    "verilog/mac.sv",
    "verilog/activation_buffer.sv",
    "verilog/weight_buffer.sv",
    "verilog/input_skew_buffer.sv",
    "verilog/scratchpad.sv",
    "verilog/tpu_command_queue.sv",
    "verilog/array_scheduler.sv",
    "verilog/tpu_controller.sv",
    "verilog/systolic_array.sv",
    "verilog/tpu.sv",
    "verilog/tpu_system.sv",
    "test/matrix_multiply_test.sv",
]


def parse_matrix(text, name):
    rows = [row.strip() for row in text.strip().split(";") if row.strip()]
    if len(rows) != T:
        raise ValueError(f"{name} must have {T} rows; got {len(rows)}")

    matrix = []
    for idx, row in enumerate(rows):
        values = [v for v in re.split(r"[\s,]+", row) if v]
        if len(values) != T:
            raise ValueError(f"{name} row {idx} must have {T} values; got {len(values)}")
        matrix.append([int(v, 0) for v in values])
    return matrix


def matmul(a, b):
    return [[sum(a[r][k] * b[k][c] for k in range(T)) for c in range(T)] for r in range(T)]


def sv_u32(value):
    return value & 0xFFFFFFFF


def write_matrix_include(path, a, b, c):
    with path.open("w", encoding="utf-8") as f:
        f.write("// Generated by scripts/run_matrix_multiply.py\n")
        f.write("// A is stored as contiguous column vectors A[:,k].\n")
        for k in range(T):
            for r in range(T):
                f.write(f"        host_write(16'd{A_BASE + k*T + r}, 32'd{sv_u32(a[r][k])});\n")

        f.write("// B is stored as contiguous row vectors B[k,:].\n")
        for k in range(T):
            for col in range(T):
                f.write(f"        host_write(16'd{B_BASE + k*T + col}, 32'd{sv_u32(b[k][col])});\n")

        f.write("// Expected C = A * B, row-major.\n")
        for r in range(T):
            for col in range(T):
                f.write(f"        expected[{r*T + col}] = 32'd{sv_u32(c[r][col])};\n")


def extract_result(output):
    rows = []
    in_block = False
    for line in output.splitlines():
        stripped = line.strip()
        if stripped == "MATRIX_RESULT_BEGIN":
            in_block = True
            continue
        if stripped == "MATRIX_RESULT_END":
            break
        if in_block:
            rows.append(stripped)
    return rows


def ensure_vcs_available():
    if shutil.which("vcs"):
        return

    raise RuntimeError(
        "VCS is not on PATH. Run this on CAEN after loading VCS, e.g. "
        "`module load vcs/2023.12-SP2-1 verdi/2023.12-SP2-1 synopsys-synth`."
    )


def run_vcs(repo_root):
    simv = repo_root / "build" / "matrix_multiply.simv"
    out_file = repo_root / "build" / "matrix_multiply.out"

    compile_cmd = [
        "vcs",
        "-sverilog",
        "-full64",
        "-kdb",
        "-lca",
        "-nc",
        "-debug_access+all",
        "+incdir+verilog/includes",
        "+incdir+verilog",
        *SOURCES,
        "-o",
        str(simv),
    ]
    subprocess.run(compile_cmd, cwd=repo_root, check=True)

    run_cmd = [str(simv), "+vcs+vcd", "+dumpfile=vcd/matrix_multiply.vcd"]
    result = subprocess.run(
        run_cmd,
        cwd=repo_root,
        check=True,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
    )
    out_file.write_text(result.stdout, encoding="utf-8")
    print(result.stdout, end="")
    return result.stdout


def main():
    parser = argparse.ArgumentParser(description="Run one 4x4 matrix multiply on the TPU testbench.")
    parser.add_argument("a", nargs="?", help="Matrix A rows separated by semicolons.")
    parser.add_argument("b", nargs="?", help="Matrix B rows separated by semicolons.")
    args = parser.parse_args()

    matrix_a = args.a or input("Enter matrix A as 4 semicolon-separated rows:\n")
    matrix_b = args.b or input("Enter matrix B as 4 semicolon-separated rows:\n")

    try:
        a = parse_matrix(matrix_a, "A")
        b = parse_matrix(matrix_b, "B")
    except ValueError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    c = matmul(a, b)

    repo_root = Path(__file__).resolve().parents[1]
    (repo_root / "build").mkdir(exist_ok=True)
    (repo_root / "vcd").mkdir(exist_ok=True)
    write_matrix_include(repo_root / "build" / "matrix_input.svh", a, b, c)

    try:
        ensure_vcs_available()
        output = run_vcs(repo_root)
    except (RuntimeError, subprocess.CalledProcessError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 127 if isinstance(exc, RuntimeError) else exc.returncode

    rows = extract_result(output)
    if rows:
        print("\nReadable result:")
        for row in rows:
            print(f"  {row}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
